apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kp660j7nq-nodejs
  janus-idp.io/tekton: kp660j7nq-nodejs
  backstage.io/kubernetes-id: kp660j7nq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kp660j7nq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
