apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kp660j7nq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kp660j7nq-nodejs 
  name: kp660j7nq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kp660j7nq-nodejs 
