apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kp660j7nq-nodejs 
  janus-idp.io/tekton: kp660j7nq-nodejs
  backstage.io/kubernetes-id: kp660j7nq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kp660j7nq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml